# 別ファイルにするまでもないゲーム用
windowrule = tag +dia4, match:title (ディアブロ IV)

windowrule = workspace 4, match:tag dia4
windowrule = pseudo on, match:tag dia4
windowrule = center on, match:tag dia4
windowrule = float yes, match:tag dia4
windowrule = fullscreen yes, match:tag dia4
