windowrule = tag +poe1, match:title (Path of Exile)
windowrule = tag +poe1, match:class (steam_app_238960)

windowrule = workspace 4, match:tag poe1
windowrule = pseudo on, match:tag poe1
windowrule = center on, match:tag poe1
