windowrule = tag +poe, match:title (Path of Exile 2)
windowrule = tag +poe, match:class (steam_app_2694490)
# windowrule = match:tag poe, float on
 
windowrule = match:tag poe2, workspace 4
windowrule = match:tag poe2, pseudo on
windowrule = match:tag poe2, center on
